name: tests_octave

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install octave
      run: sudo apt-get install octave
    - name: Test with pytest
      run: |
        cd matlab_octave
        octave toy_example.m
